### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [marlkiller/t66y_auto_register#2]
我改了一下  在actions运行  但是一直获取不到注册成功的信息诶 很奇怪  直接跑的py  没用run.sh

**Comment by marlkiller** [comment]
程序会时刻监控 “发码” 的帖子, 但并不代表时刻有人发码;
一般每周 或者节假日 发码 帖会多一些;

**Comment by ghost** [comment]
感觉actions跑好像还是不太行  跑得久了就会断 好像得加个定时

**Comment by marlkiller** [comment]
没有用过 actions, 是 Serverless 之类的么? 这种一般都会有时间限制;
建议在虚拟机内跑;
